# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/323/bin/cmake

# The command to remove a file.
RM = /snap/cmake/323/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sumit/resource_clones/sumon_vai/event

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sumit/resource_clones/sumon_vai/event

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/323/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/323/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sumit/resource_clones/sumon_vai/event/CMakeFiles /home/sumit/resource_clones/sumon_vai/event/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sumit/resource_clones/sumon_vai/event/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_exe

# Build rule for target.
test_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_exe
.PHONY : test_exe

# fast build rule for target.
test_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/build
.PHONY : test_exe/fast

avr_timer.o: avr_timer.cpp.o

.PHONY : avr_timer.o

# target to build an object file
avr_timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/avr_timer.cpp.o
.PHONY : avr_timer.cpp.o

avr_timer.i: avr_timer.cpp.i

.PHONY : avr_timer.i

# target to preprocess a source file
avr_timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/avr_timer.cpp.i
.PHONY : avr_timer.cpp.i

avr_timer.s: avr_timer.cpp.s

.PHONY : avr_timer.s

# target to generate assembly for a file
avr_timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/avr_timer.cpp.s
.PHONY : avr_timer.cpp.s

event.o: event.cpp.o

.PHONY : event.o

# target to build an object file
event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/event.cpp.o
.PHONY : event.cpp.o

event.i: event.cpp.i

.PHONY : event.i

# target to preprocess a source file
event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/event.cpp.i
.PHONY : event.cpp.i

event.s: event.cpp.s

.PHONY : event.s

# target to generate assembly for a file
event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/event.cpp.s
.PHONY : event.cpp.s

new.o: new.cpp.o

.PHONY : new.o

# target to build an object file
new.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/new.cpp.o
.PHONY : new.cpp.o

new.i: new.cpp.i

.PHONY : new.i

# target to preprocess a source file
new.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/new.cpp.i
.PHONY : new.cpp.i

new.s: new.cpp.s

.PHONY : new.s

# target to generate assembly for a file
new.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/new.cpp.s
.PHONY : new.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/test.cpp.s
.PHONY : test.cpp.s

timer.o: timer.cpp.o

.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i

.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_exe.dir/build.make CMakeFiles/test_exe.dir/timer.cpp.s
.PHONY : timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_exe"
	@echo "... avr_timer.o"
	@echo "... avr_timer.i"
	@echo "... avr_timer.s"
	@echo "... event.o"
	@echo "... event.i"
	@echo "... event.s"
	@echo "... new.o"
	@echo "... new.i"
	@echo "... new.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

